import { ArrowUpRight, Linkedin } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { getLinkedInPosts, type LinkedInPost } from '@/data/linkedinPosts';
import { profile } from '@/data/profile';
import { useTranslation } from '@/hooks/useTranslation';
export const LinkedInFollow = () => { const { language } = useTranslation(); return <Button asChild variant="outline"><a href={profile.links.activity} target="_blank" rel="noopener noreferrer"><Linkedin />{language === 'fr' ? 'Me suivre sur LinkedIn' : 'Follow me on LinkedIn'}<ArrowUpRight /></a></Button>; };
export const LinkedInPostList = ({ posts }: { posts: LinkedInPost[] }) => { const { language } = useTranslation(); return posts.length ? <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{posts.map(post => <article key={post.id} className="surface overflow-hidden flex flex-col"><div className="p-6 flex-1"><time dateTime={post.date} className="text-xs text-muted-foreground">{new Intl.DateTimeFormat(language === 'fr' ? 'fr-FR' : 'en-GB', { dateStyle: 'medium' }).format(new Date(post.date))}</time><h3 className="text-xl font-semibold mt-4">{language === 'en' ? post.title_en || post.title : post.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{language === 'en' ? post.excerpt_en || post.excerpt : post.excerpt}</p><div className="flex flex-wrap gap-2 mt-4">{post.tags.map(tag => <span key={tag} className="text-xs text-primary bg-primary/5 rounded-md px-2 py-1">{tag}</span>)}</div></div>{post.embedUrn && <iframe title={post.title} loading="lazy" src={`https://www.linkedin.com/embed/feed/update/${encodeURIComponent(post.embedUrn)}`} className="w-full h-[420px] border-0" />}<div className="p-6 pt-0"><Button asChild variant="link" className="p-0"><a href={post.url} target="_blank" rel="noopener noreferrer">{language === 'fr' ? 'Lire sur LinkedIn' : 'Read on LinkedIn'}<ArrowUpRight /></a></Button></div></article>)}</div> : <div className="surface p-7 sm:p-10 flex flex-col sm:flex-row sm:items-center justify-between gap-6"><div className="flex items-start gap-5"><Linkedin className="h-9 w-9 shrink-0 text-primary" /><h3 className="text-xl sm:text-2xl font-semibold">{language === 'fr' ? 'Suivez mon actualité sur LinkedIn' : 'Follow my updates on LinkedIn'}</h3></div><LinkedInFollow /></div>; };
export const LinkedInNews = () => { const { language } = useTranslation(); const posts = getLinkedInPosts().slice(0,3); return <><div className="flex flex-wrap items-end justify-between gap-5 mb-8"><div><p className="eyebrow">06 — {language === 'fr' ? 'Actualités' : 'News'}</p><h2 className="section-title mb-0">{language === 'fr' ? 'Actualités LinkedIn' : 'LinkedIn updates'}</h2></div>{posts.length > 0 && <LinkedInFollow />}</div><LinkedInPostList posts={posts} /><Button asChild variant="link" className="mt-5 p-0"><Link to="/actualites">{language === 'fr' ? 'Toutes les actualités' : 'All updates'}<ArrowUpRight /></Link></Button></>; };
