import { useEffect, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Menu, X, Sun, Moon, Languages } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useTranslation } from '@/hooks/useTranslation';
import { useTheme } from '@/hooks/useTheme';
import { profile } from '@/data/profile';
import { DownloadCV } from './ProfileSections';
const Navbar = () => {
  const [open, setOpen] = useState(false);
  const { pathname } = useLocation();
  const { language, setLanguage } = useTranslation();
  const { theme, toggleTheme } = useTheme();
  useEffect(() => { setOpen(false); }, [pathname]);
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const nav = language === 'fr' ? [['/', 'Accueil'], ['/cv', 'Parcours'], ['/projets', 'Projets'], ['/actualites', 'Actualités'], ['/contact', 'Contact']] : [['/', 'Home'], ['/cv', 'Experience'], ['/projets', 'Projects'], ['/actualites', 'News'], ['/contact', 'Contact']];
  const controls = <><Button variant="ghost" size="icon" onClick={toggleTheme} title={language === 'fr' ? (theme === 'light' ? 'Mode sombre' : 'Mode clair') : (theme === 'light' ? 'Dark mode' : 'Light mode')} aria-label={theme === 'light' ? 'Dark mode' : 'Light mode'}>{theme === 'light' ? <Moon /> : <Sun />}</Button><Button variant="ghost" size="sm" onClick={() => setLanguage(language === 'fr' ? 'en' : 'fr')} aria-label={language === 'fr' ? 'Switch to English' : 'Passer en français'}><Languages /><span>{language === 'fr' ? 'EN' : 'FR'}</span></Button></>;
  return <header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur-xl"><nav aria-label={language === 'fr' ? 'Navigation principale' : 'Main navigation'} className="mx-auto max-w-[1440px] px-4 sm:px-8"><div className="flex h-20 items-center justify-between gap-3"><Link to="/" className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-primary/20 bg-primary/5 font-heading text-sm font-semibold text-primary">GPM</span><span className="text-sm font-semibold leading-tight max-w-[140px] sm:max-w-none">{profile.name}</span></Link><div className="hidden xl:flex items-center gap-6">{nav.map(([url,label]) => <Link key={url} to={url} aria-current={pathname === url ? 'page' : undefined} className={`text-sm nav-link ${pathname === url ? 'text-primary font-semibold' : 'text-muted-foreground'}`}>{label}</Link>)}</div><div className="hidden xl:flex items-center gap-1">{controls}<DownloadCV className="ml-3" /></div><div className="flex xl:hidden items-center gap-1">{controls}<Button size="icon" variant="ghost" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open}>{open ? <X /> : <Menu />}</Button></div></div>{open && <div className="xl:hidden border-t border-border py-5 space-y-2">{nav.map(([url,label]) => <Button key={url} asChild variant="ghost" className="w-full justify-start"><Link to={url}>{label}</Link></Button>)}<DownloadCV className="w-full mt-4" /></div>}</nav></header>;
};
export default Navbar;
