import { ArrowUpRight, Download, Linkedin, Mail, Phone, Calendar, BarChart3, Briefcase, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Link } from 'react-router-dom';
import { profile, localized, profilePeriod } from '@/data/profile';
import { useTranslation } from '@/hooks/useTranslation';

export const SectionHeading = ({ number, title }: { number: string; title: string }) => <><p className="eyebrow">{number} — {title}</p><h2 className="section-title">{title}</h2></>;
export const DownloadCV = ({ className = '' }: { className?: string }) => { const { language } = useTranslation(); return <Button asChild className={className}><a href={profile.links.cv} download><Download />{language === 'fr' ? 'Télécharger le CV' : 'Download CV'}</a></Button>; };
export const Availability = () => { const { language } = useTranslation(); return <p className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-3 py-2 text-xs sm:text-sm text-primary"><span className="h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{localized(profile.availability, language)}</p>; };
export const BriefCards = () => { const { language } = useTranslation(); const icons = [BarChart3, Briefcase, Users]; return <div className="space-y-3">{profile.brief.map((item, i) => { const Icon = icons[i]; return <div key={item.title.fr} className="surface flex items-start gap-4 p-5">{Icon && <Icon className="mt-1 h-5 w-5 shrink-0 text-primary" />}<div><h3 className="text-base font-semibold">{localized(item.title, language)}</h3><p className="mt-1 text-sm text-muted-foreground">{localized(item.description, language)}</p></div></div>; })}</div>; };
export const ExperienceTimeline = () => { const { language } = useTranslation(); return <div className="ml-2 border-l border-border">{profile.experiences.map((exp, index) => <article key={exp.id} className="relative pb-10 pl-7 sm:pl-10 last:pb-0"><span className={`absolute -left-1.5 top-2 h-3 w-3 rounded-full border-2 border-background ${index === 0 ? 'bg-primary ring-4 ring-primary/10' : 'bg-muted-foreground'}`} /><div className={index === 0 ? 'rounded-lg border border-primary/20 bg-primary/5 p-5 sm:p-7' : 'px-5 sm:px-7'}><div className="flex flex-wrap justify-between gap-2"><p className="text-primary font-semibold">{exp.company}</p><p className="text-xs sm:text-sm text-muted-foreground">{profilePeriod(exp.start, exp.end, language)}</p></div><h3 className="mt-2 text-xl font-semibold">{localized(exp.title, language)}</h3><ul className="mt-4 space-y-2 text-sm leading-relaxed text-muted-foreground">{exp.missions.map(m => <li key={m.fr} className="flex gap-3"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-primary" /><span>{localized(m, language)}</span></li>)}</ul></div></article>)}</div>; };
export const EducationCards = ({ full = false }: { full?: boolean }) => { const { language } = useTranslation(); return <div className="grid gap-4 md:grid-cols-3">{profile.education.map(edu => <article className="surface p-6" key={edu.school}><p className="text-xs text-muted-foreground mb-3">{edu.period}</p><h3 className="font-semibold text-lg">{localized(edu.degree, language)}</h3><p className="text-sm text-primary mt-3">{edu.school}</p>{full && <div className="mt-5 text-sm leading-relaxed text-muted-foreground space-y-3"><p><strong className="text-foreground">{language === 'fr' ? 'Cours principaux : ' : 'Main courses: '}</strong>{localized(edu.courses, language)}</p><p><strong className="text-foreground">{language === 'fr' ? 'Langages et outils : ' : 'Languages and tools: '}</strong>{edu.tools}</p></div>}</article>)}</div>; };
export const SkillGroups = () => { const { language } = useTranslation(); return <><div className="grid gap-8 md:grid-cols-3">{profile.skills.map(group => <div key={group.title.fr}><h3 className="text-lg font-semibold mb-5">{localized(group.title, language)}</h3><div className="flex flex-wrap gap-2">{group.items.map(item => <span className="rounded-md border border-border bg-card px-3 py-2 text-sm" key={item.fr}>{localized(item, language)}</span>)}</div></div>)}</div><div className="mt-10 flex flex-wrap gap-x-10 gap-y-4 border-t border-border pt-7">{profile.languages.map(lang => <p key={lang.name.fr} className="text-sm"><strong>{localized(lang.name, language)}</strong><span className="text-muted-foreground"> · {localized(lang.level, language)}</span></p>)}</div></>; };
export const ContactBlock = () => { const { language, t } = useTranslation(); return <div className="grid gap-10 md:grid-cols-2"><div><p className="eyebrow">07 — Contact</p><h2 className="section-title">{t('contact.title')}</h2><p className="text-muted-foreground max-w-md leading-relaxed">{t('contact.subtitle')}</p></div><div className="space-y-5"><a className="flex items-center gap-3 text-lg break-all hover:text-primary" href={`mailto:${profile.email}`}><Mail className="h-5 w-5 shrink-0 text-primary" />{profile.email}</a><a className="flex items-center gap-3 hover:text-primary" href={profile.phoneHref}><Phone className="h-5 w-5 text-primary" />{profile.phone}</a><a className="flex items-center gap-3 hover:text-primary" href={profile.links.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin className="h-5 w-5 text-primary" />LinkedIn<ArrowUpRight className="h-4 w-4" /></a><div className="flex flex-wrap gap-3 pt-3"><Button asChild><a href={profile.links.calendly} target="_blank" rel="noopener noreferrer"><Calendar />{t('hero.cta.calendly')}</a></Button><Button asChild variant="outline"><Link to="/contact">{language === 'fr' ? 'Formulaire de contact' : 'Contact form'}<ArrowUpRight /></Link></Button></div></div></div>; };
