// This file must reflect the LinkedIn profile. Update all bilingual profile facts here.
import type { Language } from "@/hooks/useTranslation";
export type Localized = { fr: string; en: string };
export const profile = {
  "name": "Gabriel Pelenga Mangi",
  "title": {
    "fr": "Business Analyst & Spécialiste Power BI",
    "en": "Business Analyst & Power BI Specialist"
  },
  "tagline": {
    "fr": "Passionné par la transformation des données en insights stratégiques pour optimiser les performances business et automatiser les processus.",
    "en": "Passionate about transforming data into strategic insights to optimize business performance and automate processes."
  },
  "availability": {
    "fr": "En recherche d'un CDI/CDD pour Octobre 2026",
    "en": "Seeking a permanent (CDI) or fixed-term (CDD) contract for October 2026"
  },
  "qualification": {
    "fr": "Diplômé du Mastère Data Science in Business, en recherche d'un CDI/CDD pour Octobre 2026",
    "en": "cv.header.subtitle"
  },
  "current": {
    "fr": "Actuellement : Analyste métier & Analyste qualité des données chez Partoo",
    "en": "Currently: Business Analyst & Data Quality Analyst at Partoo"
  },
  "photo": "/lovable-uploads/a800ede8-6357-4e94-b0f9-df456a52625c.png",
  "email": "gabrielpelenga@gmail.com",
  "phone": "06.72.62.01.65",
  "phoneHref": "tel:+33672620165",
  "links": {
    "cv": "/CV_Gabriel_PELENGA_MANGI.pdf",
    "linkedin": "https://www.linkedin.com/in/gabriel-pelenga-mangi-820487182/",
    "activity": "https://www.linkedin.com/in/gabriel-pelenga-mangi-820487182/recent-activity/all/",
    "calendly": "https://calendly.com/gabrielpelenga/30min"
  },
  "about": [
    {
      "fr": "Spécialiste en analyse de données commerciales qui combine expertise technique et vision stratégique pour transformer les données en décisions pertinentes.",
      "en": "Commercial data analysis specialist combining technical expertise and strategic vision to transform data into relevant decisions."
    },
    {
      "fr": "Professionnel polyvalent avec une solide expérience en gestion de projets, analyse commerciale et automatisation de process et de données, cherchant à déployer ses compétences en data science et business intelligence dans un environnement stimulant.",
      "en": "Versatile professional with solid experience in project management, business analysis and process & data automation, seeking to deploy data science and business intelligence skills in a stimulating environment."
    }
  ],
  "brief": [
    {
      "title": {
        "fr": "Business Analyst avec expertise BI",
        "en": "Business Analyst with BI expertise"
      },
      "description": {
        "fr": "Analyse de données, visualisation et automatisation",
        "en": "Data analysis, visualization and automation"
      }
    },
    {
      "title": {
        "fr": "En recherche d'un CDI/CDD",
        "en": "Seeking a permanent/fixed-term contract"
      },
      "description": {
        "fr": "Pour Octobre 2026",
        "en": "For October 2026"
      }
    },
    {
      "title": {
        "fr": "Leadership et esprit d'équipe",
        "en": "Leadership and team spirit"
      },
      "description": {
        "fr": "Capitaine d'équipe sportive, gestion de projets",
        "en": "Sports team captain, project management"
      }
    }
  ],
  "tools": [
    "Power BI",
    "SQL",
    "Python",
    "Salesforce",
    "Streamlit",
    "Databricks",
    "Tableau",
    "Excel"
  ],
  "experiences": [
    {
      "id": "partoo",
      "company": "Partoo",
      "title": {
        "fr": "Analyste métier & Analyste qualité des données",
        "en": "Business Analyst & Data Quality Analyst"
      },
      "start": "2025-09",
      "end": "2026-09",
      "missions": [
        {
          "fr": "Gestion de portefeuille par marché (Europe, Moyen-Orient, Amérique Latine)",
          "en": "Portfolio management by market (Europe, Middle East, Latin America)"
        },
        {
          "fr": "Reportings de KPI commerciaux : CA généré par les équipes, Nombre de RDV fixés",
          "en": "Commercial KPI reporting: revenue generated by teams, number of meetings scheduled"
        },
        {
          "fr": "Nettoyage du CRM & Portefeuille",
          "en": "CRM & Portfolio cleanup"
        },
        {
          "fr": "Création de Dashboard Streamlit & SalesForce",
          "en": "Streamlit & SalesForce Dashboard creation"
        }
      ]
    },
    {
      "id": "verisure",
      "company": "Vérisure",
      "title": {
        "fr": "Analyste BI & Analyste performance commerciale",
        "en": "BI Analyst & Commercial Performance Analyst"
      },
      "start": "2024-09",
      "end": "2025-01",
      "missions": [
        {
          "fr": "Gestion de données commerciales",
          "en": "Commercial data management"
        },
        {
          "fr": "Rapport d'analyse (performance commerciales)",
          "en": "Analysis reports (commercial performance)"
        },
        {
          "fr": "Analyses des KPI commerciales",
          "en": "Commercial KPI analysis"
        },
        {
          "fr": "Récupération de données commerciales",
          "en": "Commercial data retrieval"
        }
      ]
    },
    {
      "id": "greenflex",
      "company": "Greenflex / Total Energie",
      "title": {
        "fr": "Chef de projet & Analyste métier",
        "en": "Project Manager & Business Analyst"
      },
      "start": "2024-04",
      "end": "2024-09",
      "missions": [
        {
          "fr": "Gestion de paramétrage de données clients",
          "en": "Client data configuration management"
        },
        {
          "fr": "Gestion et Pilotage de projet en agilité",
          "en": "Agile project management and steering"
        },
        {
          "fr": "Animation de réunion commerciale",
          "en": "Commercial meeting facilitation"
        },
        {
          "fr": "Animation de Webinaire clients",
          "en": "Client webinar facilitation"
        }
      ]
    },
    {
      "id": "koesio",
      "company": "Koésio Corporate IT",
      "title": {
        "fr": "Analyste métier & Développeur commercial",
        "en": "Business Analyst & Business Developer"
      },
      "start": "2022-11",
      "end": "2023-10",
      "missions": [
        {
          "fr": "Gestion de la clientèle (65 clients dont 3 grands comptes)",
          "en": "Client management (65 clients including 3 key accounts)"
        },
        {
          "fr": "Reportings de KPI commerciaux : taux de clic, retour sur investissement, CA généré",
          "en": "Commercial KPI reporting: click rate, ROI, revenue generated"
        },
        {
          "fr": "Prospection Téléphonique (30 appels par jours)",
          "en": "Phone prospecting (30 calls per day)"
        },
        {
          "fr": "Rendez-vous en clientèle (présentation des solutions)",
          "en": "Client meetings (solution presentations)"
        }
      ]
    }
  ],
  "education": [
    {
      "school": "Eugenia School (Paris 10)",
      "degree": {
        "fr": "MSc Analytics for Business",
        "en": "MSc Analytics for Business"
      },
      "period": "2024 – 2026",
      "courses": {
        "fr": "Collecte, visualisation et analyse de données, Programmation, Stratégie, Finance, Marketing",
        "en": "Data collection, visualization and analysis, Programming, Strategy, Finance, Marketing"
      },
      "tools": "Python, SQL, PowerBI, Agile Methodology, Databricks, Tableau, Target Process"
    },
    {
      "school": "CFA Codis (Paris 10)",
      "degree": {
        "fr": "Bachelor en management commercial et marketing",
        "en": "Bachelor in Commercial Marketing Management"
      },
      "period": "2022 – 2023",
      "courses": {
        "fr": "Marketing, Statistiques, Communication, Négociation, Management, E-commerce",
        "en": "Marketing, Statistics, Communication, Negotiation, Management, E-commerce"
      },
      "tools": "Python, Excel, PowerPoint, Canva, SEO/SEA, SQL"
    },
    {
      "school": "Lycée Van Gogh (Paris 10)",
      "degree": {
        "fr": "BTS Négociation et digitalisation de la relation client",
        "en": "BTS in Digital Client Relationship & Negotiation"
      },
      "period": "2020 – 2022",
      "courses": {
        "fr": "Marketing, Négociation, Communication, E-commerce",
        "en": "Marketing, Negotiation, Communication, E-commerce"
      },
      "tools": "Excel, PowerPoint, Canva, PrestaShop, WordPress"
    }
  ],
  "skills": [
    {
      "title": {
        "fr": "Analyse de Données",
        "en": "Data Analysis"
      },
      "items": [
        {
          "fr": "Python",
          "en": "Python"
        },
        {
          "fr": "SQL",
          "en": "SQL"
        },
        {
          "fr": "Power BI",
          "en": "Power BI"
        },
        {
          "fr": "Databricks",
          "en": "Databricks"
        },
        {
          "fr": "Tableau",
          "en": "Tableau"
        },
        {
          "fr": "Excel",
          "en": "Excel"
        }
      ]
    },
    {
      "title": {
        "fr": "Business Intelligence",
        "en": "Business Intelligence"
      },
      "items": [
        {
          "fr": "KPI commerciaux",
          "en": "Commercial KPIs"
        },
        {
          "fr": "Reporting",
          "en": "Reporting"
        },
        {
          "fr": "Analyse de performance",
          "en": "Performance Analysis"
        },
        {
          "fr": "Gestion de données",
          "en": "Data Management"
        },
        {
          "fr": "Visualisation de données",
          "en": "Data Visualization"
        }
      ]
    },
    {
      "title": {
        "fr": "Gestion & Communication",
        "en": "Management & Communication"
      },
      "items": [
        {
          "fr": "Méthode Agile",
          "en": "Agile Methodology"
        },
        {
          "fr": "Gestion de projet",
          "en": "Project Management"
        },
        {
          "fr": "Animation de réunions",
          "en": "Meeting Facilitation"
        },
        {
          "fr": "Webinaires",
          "en": "Webinars"
        },
        {
          "fr": "Présentation client",
          "en": "Client Presentations"
        },
        {
          "fr": "Target Process",
          "en": "Target Process"
        }
      ]
    }
  ],
  "languages": [
    {
      "name": {
        "fr": "Français",
        "en": "French"
      },
      "level": {
        "fr": "Natif",
        "en": "Native"
      }
    },
    {
      "name": {
        "fr": "Anglais",
        "en": "English"
      },
      "level": {
        "fr": "Professionnel",
        "en": "Professional"
      }
    },
    {
      "name": {
        "fr": "Espagnol",
        "en": "Spanish"
      },
      "level": {
        "fr": "Intermédiaire",
        "en": "Intermediate"
      }
    }
  ],
  "interests": {
    "fr": "Sports (Basketball, Football, Boxe Anglaise)",
    "en": "Sports (Basketball, Football, Boxing)"
  },
  "associations": [
    {
      "name": "Boxing Club Poissy",
      "period": {
        "fr": "2022 – 2023 (1 an)",
        "en": "2022 – 2023 (1 year)"
      },
      "missions": []
    },
    {
      "name": "Basketball",
      "period": {
        "fr": "2014 – 2022 (7 ans)",
        "en": "2014 – 2022 (7 years)"
      },
      "title": {
        "fr": "Capitaine des U-19",
        "en": "U-19 Captain"
      },
      "missions": [
        {
          "fr": "Support du coach dans les diverses opérations de communication et de management de l'équipe",
          "en": "Supporting the coach in team communication and management operations"
        },
        {
          "fr": "Vainqueurs de la coupe régionale en 2018 et 2020",
          "en": "Regional cup winners in 2018 and 2020"
        }
      ]
    }
  ]
};
export const localized = (value: Localized, language: Language) => value[language];
const months = { fr: ["Janv.", "Févr.", "Mars", "Avr.", "Mai", "Juin", "Juil.", "Août", "Sept.", "Oct.", "Nov.", "Déc."], en: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] };
export const profilePeriod = (start: string, end: string, language: Language) => [start, end].map(date => { const [year, month] = date.split("-"); return `${months[language][Number(month)-1]} ${year}`; }).join(" – ");
